### ISSUE TITLE
Chess 

### ISSUE THREAD

**Issue by E-07** [Acnologla/asura#11]
Faz tbm a msm coisa que eu falei no **connect4** e no **ttt**

---
Olha um bug ae 
![20201001_171107](https://user-images.githubusercontent.com/65204624/94858324-44c65f00-0409-11eb-84b6-5554ba2e8764.jpg)

**Comment by E-07** [comment]
Se isso n for bug sorry

**Comment by remfanboy** [comment]
No **ttt** e **connect4** não há como fazer isso
