### ISSUE TITLE
connect4

### ISSUE THREAD

**Issue by E-07** [Acnologla/asura#4]
Poderia ter um jeito de o usuário mencionado aceitar a partida de ``connect4``E também uma forma de não precisa marcar no comando so falar o nome. 

Exemplo 1

> **Usuário:** "j!connect4 @Chiyoku"
**Asura:** "Por favor, os dois usuários teve reagi na reação para poder jogar."

---

Exemplo 2

> **Usuário:** "j!connect4 Chiyoku " // Sem Menção

**Comment by Chiyoku** [comment]
É uma boa ideia, iremos implementar isso na proxima atualização. Muito obrigado pela sugestão!
Fecharemos essa issue quando a feature for implementada.

**Comment by Acnologla** [comment]
O connect4 é um comando onde o cara pode jogar varios jogos ao mesmo tempo, ele nao tem que esperar um acabar para começar outro, entao caso o usuario mencionado nao queira jogar ele pode simplismente nao fazer nada, então adicionar um tipo de "confirmação" no final só ia atrasar todos.
